from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Structured implementation plan generated by PlannerAgent.
    Used throughout the entire AutoDev AI pipeline.
    """

    title: str = Field(
        ...,
        description="Project title"
    )

    description: str = Field(
        ...,
        description="Short project overview"
    )

    project_type: str = Field(
        ...,
        description="web, api, cli, desktop, mobile, ai, library, etc."
    )

    language: str = Field(
        ...,
        description="Primary programming language"
    )

    framework: str = Field(
        ...,
        description="Main framework"
    )

    database: Optional[str] = Field(
        default=None,
        description="Database technology"
    )

    authentication: Optional[str] = Field(
        default=None,
        description="Authentication method"
    )

    deployment: Optional[str] = Field(
        default=None,
        description="Deployment strategy"
    )

    architecture: Optional[str] = Field(
        default=None,
        description="Architecture style"
    )

    testing: Optional[str] = Field(
        default=None,
        description="Testing framework"
    )

    dependencies: List[str] = Field(
        default_factory=list,
        description="Major packages required"
    )

    features: List[str] = Field(
        default_factory=list,
        description="Core application features"
    )

    steps: List[str] = Field(
        default_factory=list,
        description="Implementation order"
    )