from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Structured implementation plan generated by PlannerAgent.
    Used throughout the AutoDev AI pipeline.
    """

    title: str = Field(
        ...,
        description="Project title",
    )

    description: str = Field(
        ...,
        description="Short project overview",
    )

    project_type: str = Field(
        ...,
        description="Type of project such as CLI, web, API, desktop, mobile, AI, or library",
    )

    language: str = Field(
        ...,
        description="Primary programming language",
    )

    framework: Optional[str] = Field(
        default=None,
        description="Main framework, if required",
    )

    database: Optional[str] = Field(
        default=None,
        description="Database technology, if required",
    )

    authentication: Optional[str] = Field(
        default=None,
        description="Authentication method, if required",
    )

    deployment: Optional[str] = Field(
        default=None,
        description="Deployment strategy, if required",
    )

    architecture: Optional[str] = Field(
        default=None,
        description="Architecture style, if required",
    )

    testing: Optional[str] = Field(
        default=None,
        description="Testing framework or strategy",
    )

    dependencies: List[str] = Field(
        default_factory=list,
        description="Packages and dependencies actually required by the project",
    )

    features: List[str] = Field(
        default_factory=list,
        description="Core features explicitly required by the user",
    )

    steps: List[str] = Field(
        default_factory=list,
        description="Implementation steps in execution order",
    )