import { useCallback, useEffect, useState } from "react";
import { FolderCode, RefreshCw } from "lucide-react";

import {
  deleteProject,
  getProjects,
} from "../api/api";
import ProjectList from "../components/projects/ProjectList";

export default function Projects() {
  const [projects, setProjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [deletingId, setDeletingId] = useState(null);
  const [error, setError] = useState("");

  const loadProjects = useCallback(async () => {
    try {
      setLoading(true);
      setError("");

      const data = await getProjects();

      setProjects(
        Array.isArray(data?.projects)
          ? data.projects
          : [],
      );
    } catch (err) {
      console.error(
        "Failed to load projects:",
        err,
      );

      setError(
        err?.response?.data?.detail ||
          "Unable to load projects.",
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
  const timer = setTimeout(() => {
    loadProjects();
  }, 0);

  return () => clearTimeout(timer);
}, [loadProjects]);

  const handleDelete = async (project) => {
    const confirmed = window.confirm(
      `Delete "${project.title}"? This action cannot be undone.`,
    );

    if (!confirmed) {
      return;
    }

    try {
      setDeletingId(project.id);
      setError("");

      await deleteProject(project.id);

      setProjects((current) =>
        current.filter(
          (item) => item.id !== project.id,
        ),
      );
    } catch (err) {
      console.error(
        "Failed to delete project:",
        err,
      );

      setError(
        err?.response?.data?.detail ||
          "Unable to delete project.",
      );
    } finally {
      setDeletingId(null);
    }
  };

  return (
    <div className="aio-workspace">
      <div className="aio-main">
        <section className="aio-projects-page">
          <div className="aio-projects-header">
            <div>
              <div className="aio-section-label">
                <FolderCode size={12} />
                PROJECTS
              </div>

              <h1>Generated Projects</h1>

              <p>
                Browse, inspect, and manage applications
                generated by AutoDev AI.
              </p>
            </div>

            <button
              type="button"
              className="aio-projects-refresh"
              onClick={loadProjects}
              disabled={loading}
            >
              <RefreshCw
                size={14}
                className={
                  loading ? "aio-spin" : ""
                }
              />
              Refresh
            </button>
          </div>

          {error && (
            <div
              className="aio-projects-error"
              role="alert"
            >
              {error}
            </div>
          )}

          <ProjectList
            projects={projects}
            loading={loading}
            deletingId={deletingId}
            onDelete={handleDelete}
          />
        </section>
      </div>
    </div>
  );
}